### ISSUE TITLE
error SC

### ISSUE THREAD

**Issue by vbatcnam** [vbatcnam/minimonde#11]
J'ai une erreur SC
 TypeError: p.bindTo is not a function SugarCubes.js:3336:17
addBranch
http://jeanferdysusini.free.fr/SugarCubes.js:3336:17
react
http://jeanferdysusini.free.fr/SugarCubes.js:4405:9
SC_Machine/this.timer</<
http://jeanferdysusini.free.fr/SugarCubes.js:4187:41

**Comment by LordManta** [comment]
Ce n'est pas une véritable erreur SugarCubes JS tu ajoute des chaînes de caractères à la machine ... ce ne sont pas des programmes valides. Je vais rajouter un mécanisme de tapage pour avoir une meilleure remonté d'erreur...

**Comment by vbatcnam** [comment]
ok merci :)
