### ISSUE TITLE
problème getEltSVG() 

### ISSUE THREAD

**Issue by vbatcnam** [vbatcnam/minimonde#5]
J'ai un problème avec la fonction getEltSVG() dans herbe.js (le problème sera partout dès que je voudrais avoir accès au svg)

Lorsque j'appelle cette fonction, le svg n'est pas entièrement chargé

si je fais 
	for(var i = 0; i<5; i++){
	let herbe = new Herbe(i+1);
	herbe.draw(i+2, i+4);
	**window.addEventListener("load", function(evt){**
		var eltSvg = herbe.getEltSVG();
		console.log("eltSvg après return de getEltSVG");
		console.log(eltSvg);
		herbe.getEchelle(eltSvg);
	})
}
Est-ce que SC évite de faire window.addEventListene... ?

Peut-être que je dois repenser mes fonctions avec des SC.quelquechose

**Comment by LordManta** [comment]
Il faut gérer un mécanisme de synchronisation sur le chargement.
Regarde la démo ici :
http://jeanferdysusini.free.fr/SC_Demo9.html

J'ai un début de mécanique intégrée dans SC_Tools.js...
