### ISSUE TITLE
sugaCubes

### ISSUE THREAD

**Issue by vbatcnam** [vbatcnam/minimonde#7]
http://jeanferdysusini.free.fr/SugarCubes.js
Ce lien est-il à jour ? 
J'ai vu que tu travaillais sur celui de github ;)

**Comment by LordManta** [comment]
C’est toujours le lien à utiliser …
À de rares exceptions près, la version en ligne est postée uniquement quand elle est stable.
Ce n’est pas le cas du GitHub.
Donc gardes le lien.
Si par contre il y a un soucis n’hésite pas à me le signaler.

**Comment by LordManta** [comment]
Non je n’ai pas vu la modification.
Mais globalement ce n’est pas une bonne idée. Utiliser me c’est un raccourci pour écrire vite et mal :)
En fait dans une valeur d’événement il faut envoyer des valeurs non mutables qui sont généralement une reproduction de l’état de l’objet d’un cube… Comme écrire proprement cela en SugarCubes peut s’avérer pénible je prends souvent le raccourcis this.me = this…
Mais c’est une mauvaise façon de le faire.

Par contre je veux bien voir la modification pour voir si je peux/veux ;-) l’intégrer…

**Comment by vbatcnam** [comment]
c'est dans sugarCubes.svg qui est avec le casseBrique (j'y ai fait une issue)

**Comment by vbatcnam** [comment]
Donc je retire SC.my("me") 
SC.actionOn(vacheMange, SC.my("me"), SC.my("eaten"), undefined, SC.forever)
devient
SC.actionOn(vacheMange, SC.my("eaten"), undefined, SC.forever)

C'est bien ça ?
autant faire propre de suite et ne pas prendre des mauvaises habitude ;)

**Comment by LordManta** [comment]
Ce n’est pas ce que je dis…

SC.my("me")

sert a dire que la valeur manipulée par le programme c’est l’objet du cube lui même.
Le SC.my("me") si tu regardes est essentiellement utilisé dans les generate()…
Donc SC.action() ne devrait pas en avoir.
Syntax :
SC.action(
     Configuration événementielle positive (en général la présence d’un simple événement)
    , une action atomique (c’est une fonction javascript, donc ça peut être une méthode de l’objet associé au cube SC.my("nom_de_la_méthode")). Le rôle de cette fonction atomique est de traiter les valeurs de la configuration (l’événement) si celle-ci est présente.
    , une autre action atomique exécutée appelé si la configuration (l’événement) n’est pas présente et donc qu’il n’y a pas de valeur
    , un nombre d’instants (facultatif) de traitement : SC.forever si infini, c’est à dire réaction à tous les instants
     )

Donc je ne comprends pas ce que serait SC.actionOn(vacheMange, SC.my("me"), SC.my("eaten"), undefined, SC.forever)
Car SC.my("me") est une valeur et n’a aucune raison d’apparaitre ici.

Les seuls endroit où SC.my("me") peut apparaitre ce sont dans les SC.generate(un_evenement, SC.my("me")) .

Par exemple dans le dessin du canvas : SC.generete(drawAll, SC.my("me")) ce qui permet au cube gérant le dessin du canvas d’appeler la méthode draw sur le cube qui a généré l’événement drawAll.

J’espère que c’est plus clair.

**Comment by vbatcnam** [comment]
Ok j'ai compris :)

Du coup je met quoi à la place de this.me = this; ?

=====================
Ais-je bien compris ?
SC.actionOn(evt, actionDeclancheSiEvtPresent, actionDeclancheSiEvtAbsant, nbreDinstant) 

Du coup je reprends pour l'herbe : Quand la vache me mange, je meurt
SC.actionOn(JeMange, SC.my("eaten"), undefined, SC.forever);

au fait... tu n'avais pas dit que SC.actionOn il valait mieux ne pas l'utiliser ? 
Que faut-il faire à la place ?

**Comment by LordManta** [comment]
Salut,

Réponses dans le corps du mail ...

> Le 15 juil. 2018 à 11:14, vbatcnam <notifications@github.com> a écrit :
> 
> Ok j'ai compris :)
> 
> Du coup je met quoi à la place de this.me = this; ?
> 
> 

Regarde ce que j’ai fait pour les murs dans la branches spécifique du casseBrique :
Par exemple pour l’affichage, je commence à créer un objet qui sera échanger : le drawer qui devient une propriété de l’objet.
      this.drawer = {};
      Object.defineProperty(this.drawer, "drawSelf"
                                , {enumerable:false
                                   , value:this.draw.bind(this)
                                   , writable: false
                                   }
                                );
Sur cet objet j’ajoute une unique propriété en lecture seule qui est la méthode draw du mur correctement « bindée »…
Ça permet à un objet chargé de dessiner (l’objet zoneDeJeu) de dessiner l’objet mur (en appelant sa méthode draw()) sans prendre le risque de pouvoir faire un effet de bord sur l’objet mur puisque zoneDeJeu n’aura pas de référence directe sur l’objet mur.
Quand j’envoie une référence sur l’objet avec SC.my("me") et this.me = this préalablement, en fait j’envoie une référence sur tout l’objet mur. Comme je connais parfaitement mon modèle je sais que je ne dois pas faire d’effet de bords dessus et donc je me dis ça peut suffire…
Mais dans l’absolue ce n’est pas propre et potentiellement dangereux pour le modèle d’exécution.
> =====================
> Ais-je bien compris ?
> SC.actionOn(evt, actionDeclancheSiEvtPresent, actionDeclancheSiEvtAbsant, nbreDinstant)
> 
> 

Oui c’est ça.

> Du coup je reprends pour l'herbe : Quand la vache me mange, je meurt
> SC.actionOn(JeMange, SC.my("eaten"), undefined, SC.forever);
> 
> 

Ça par contre ça nécessite un peu plus de réflexion je pense. L’herbe est responsable de son « destin » et la vache du sien… Je dirais que c’est un peu la façon de réfléchir de SugarCubes…
Donc on devrait dire la vache mange … Elle envoie un événement pour signifier qu’elle mange (c’est sa décision, elle en est responsable). L’herbe écoute de décide d’être mangée. Pour moi ça c’est la décision de l’herbe.
Donc oui, on peut envisager que la vache émette l’événement JeMange par exemple avec une valeur qui sont les coordonnées de l’herbe mangée par la vache :

SC.generate(JeMange, {x: , y:})…

Et en parallèle l’herbe écoute l’événement JeMange et regarde si c’est elle qui doit être mangée : 

SC.actionOn(JeMange, SC.my("eaten")), undefined, SC.forever)

Chaque fois que l’événement JeMange sera émis par la vache.
La méthode eaten() de chaque herbe sera appelée, elle regardera par exemple si les coordonnées envoyée par la vache sont celle de l’herbe concernée alors elle traite sa disparition les autres ne font rien.
> au fait... tu n'avais pas dit que SC.actionOn il valait mieux ne pas l'utiliser ?
> Que faut-il faire à la place ?
> 
> 

Le modèle de ActionOnEvent est plein de risques potentiels (comme pour le this.me) voir plus. Il y a un autre modèle à base de cellules qu’il faudrait utiliser pour encapsuler les propriétés des objets javascript proprement. Mais Ce n’est pas encore complètement au point et c’est beaucoup plus contraignant tant que je n’ai pas fini la partie purement langage des SugarCubes (le fameux SC.lang) donc je vais pas trop t’en parler ici et pour le moment on continue avec le actionOn :-).

a+,

—
Jean-Ferdy
